ecommerce_site/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns =[
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
    path('cart_delete/<int:product_id>/', views.cart_delete, name="cart_delete"),
]

ecommerce_site/ecommerce_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecommerceapp.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_site/ecommerceapp/urls.py
from . import views
from django.urls import path

app_name = 'ecommerceapp'
urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:prod_slug>/', views.ProdDetail, name='prod_category'),

]

ecommerce_site/search_app/urls.py
from django.urls import path, include
from . import views
app_name = 'search_app'
urlpatterns = [
    path('', views.SearchRes, name='searchresult'),
]

ecommerce_site/cart/models.py
from django.db import models
from ecommerceapp.models import Products


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=200, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_site/ecommerceapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField( blank=True)
    slug = models.SlugField(max_length=150, unique=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerceapp:products_by_category', args=[self.slug])


class Products(models.Model):

    name = models.CharField(max_length=150, unique=True)
    description = models.TextField( blank=True)
    slug = models.SlugField(max_length=150, unique=True)
    image = models.ImageField(upload_to='product', blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('ecommerceapp:prod_category', args= [self.category.slug, self.slug])

ecommerce_site/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_site/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerceapp.models import Products
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product, quantity=1,
            cart=cart
        )
        cart_item.save(),
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def cart_delete(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_site/ecommerceapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Products
from django.core.paginator import Paginator, InvalidPage, EmptyPage


# Create your views here.

def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Products.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Products.objects.all().filter(available=True)
    paginator = Paginator(products_list, 9)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'categories.html', {'category': c_page, 'products': products})


def ProdDetail(request, c_slug, prod_slug):
    try:
        product = Products.objects.get(category__slug=c_slug, slug=prod_slug)
    except Exception as E:
        raise E

    return render(request, 'product.html', {'product': product})

ecommerce_site/search_app/views.py
from django.shortcuts import render
from ecommerceapp.models import Products
from django.db.models import Q


# Create your views here.

def SearchRes(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html', {'query':query, 'products':products})

ecommerce_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/custom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b905cb5fde.js" crossorigin="anonymous"></script>
    <meta name="description" content=" {% block metadescription %} {% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class=" container ">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block body %}
{% endblock %}
 </div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>



</body>
</html>

ecommerce_site/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

       This is the cart page, proceed to preview your items and place the order

{% endblock %}


{% block title %}
   Cart - Mega Cart
{% endblock %}

{% block body %}
    {% if not cart_items %}
    <div>
        <div class="text-center">
            <br>
         <h1 class="text-center my_title">
             Your Shopping Cart is Empty
         </h1>
            <br>
         <p class="text-center">
             Please Click <a href="{% url 'ecommerceapp:allProdCat' %}">Here</a> To Continue Shopping
         </p>

    </div>
        </div>

    {% else %}
        <div>
            <div class="text-center">
                <br>

             <h1 class="text-center my_title">
                 Your Shopping Cart
             </h1>
                <br>

            </div>

<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">

            <table class="table my_custom_table">
                <thead class="my_custom_head">
                    <tr>
                      <th colspan="5">
                          Your Items
                      </th>
                    </tr>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <th>
                            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class=" float-left rounded custom-image " width="80px" height="100px"></a>
                        </th>
                        <td class="my_custom_table">
                            {{cart_item.product.name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            Price:${{cart_item.product.price }}
                            <br>
                            Qty: {{cart_item.quantity}} x ${{cart_item}}
                        </td>

                            <td>
                                $ {{cart_item.sub_total}}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                            <td>
                             &nbsp;<a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-circle-plus"></i></a>
                             &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">  <i class="fa-solid fa-circle-minus"></i></a>
                             &nbsp;<a href="{% url 'cart:cart_delete' cart_item.product.id %}" class=custom_icon"> <i class="fa-solid fa-trash-can custom_icon"></i></a>

                            </td>
                            {% else %}

                                <td>
                               &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-circle-minus"></i></a>
                              &nbsp;<a href="{% url 'cart:cart_delete' cart_item.product.id %} " class=custom_icon"> <i class="fa-solid fa-trash-can"></i></a>

                            </td>
                        {% endif %}
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-5 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_head">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
                </thead>
                    <tbody>
                        <tr>
                            <td>
                                Please Review Your Cart Items Before Proceeding To Checkout
                            </td>
                        </tr>
                    <tr>
                        <td class="text-left">
                            Your Total is :<b>{{ total }}</b>

                        </td>
                    </tr>
                    </tbody>
            </table>
            <div class="mx_auto">
                <a href="{% url 'ecommerceapp:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
            </div>
        {% endif %}
        </div>
    </div>
 </div>

{% endblock %}

ecommerce_site/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}

        {{ category.description|truncatewords:200}}

    {% else %}
        Hi and a huge welcome from Team Mega Cart!
        We're thrilled to have you with us. Get ready for a memorable time and a great experience.

    {% endif %}
{% endblock %}

{% block title %}

    {% if category %}
        {{category.name}} - Mega Cart

    {% else %}
        Checkout our new products
    {% endif %}
{% endblock %}

{% block body %}
 {% if category %}

<div>
    <div class="row my_row">
        <div class="mx_auto">
               <p> <a href="{% url 'ecommerceapp:allProdCat' %}">All Product Categories</a></p>

        </div>
    </div>
</div>
    {% endif %}


<div class="">
         {% if category %}
            <img src="{{category.image.url}}" alt="{{category.name}}" width="100%" height="550px" ><br>
     </div>
<br>

<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
         <p class="text-justify"> {{ category.description }}</p>
</div>

        {% else %}

    <div>
          <img class=" my_image" src="{%  static 'imgs/MEGA CART.png' %}" alt="our products" width="100%" height="300px">
    </div>
    <br>
        <div>
            <h1 class="text-center my_title">Sweet Offers For You</h1><br>
            <p class="text-justify" >We believe in simplifying your shopping experience without compromising on excellence.
            Feel free to browse, discover, and indulge in the joy of finding exactly what you've been looking for.</p><br>
        </div>

        {% endif %}

<div class="container">
    <div class="row mx_auto">

        {% for product in products.object_list  %}

        <div class="my_bottom_margin col-sm-4 ">
            <div class="card text-center" style="min-width:14rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{ product.image.url }}" alt="{{product.name}}" style= "width:50%; height:200px;" ></a>

             <div class="card-body">

                <h3>{{product.name}}</h3>
                <p class="text-justify">${{product.price}}</p>
            <br><br>
            </div>

             </div>

            </div>
        {% endfor %}
    </div>

        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                    <a href="?page={{pg}}" class=" btn btn-light btn-sm {% if products.number == pg %} active {% endif %}}">{{pg}}</a>
                {% endfor %}
            </div>

        {% endif %}

        </div>

    <br>
</div>
{% endblock %}

ecommerce_site/templates/footer.html
<footer class="mt-auto">
  <div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Mega Cart pvt ltd. All rights Reserved</p>
</div>


</footer>
<body class="d-flex flex-column min-vh-100" >

ecommerce_site/templates/header.html
{% load static %}

<header>
    <center>
        <a href="{% url 'ecommerceapp:allProdCat' %} "><img src="{% static 'imgs/logo.png' %}" alt="logo image" width="100px" height="100px"></a>
    </center>
</header>

ecommerce_site/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>

        <li class="nav-item dropdown  {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>

          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecommerceapp:allProdCat' %}">All Products</a></li>

            {% for catg in links %}

              <li><a class="dropdown-item" href="{{catg.get_url}}">{{catg.name}}</a></li>
                    {% endfor %}
          </ul>

        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
        <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
         {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchresult' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce_site/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{product.description|truncatewords:200}}

{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}} - Mega Cart
    {% endif %}
{% endblock %}

{% block body %}
<div class="row my_prod_row">
     <div class="mx_auto">
        <p>
            <a href="{% url 'ecommerceapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}
        </p>
     </div>
<div class="container">
<br><br>

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:12 rem">
            <img src="{{product.image.url}}" alt="{{product.name}}"><br>
        </div>
    </div>

        <div class=" col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
               <h1 class="my_prod_title">{{product.name}}</h1><br>
                 <p>$ {{product.price}}</p>

                    <p class="my_title">Product Description:</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>

                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b> Out of stock</b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a> <br> <br> <br>
                {% endif %}
       </div>
    </div>
</div>
</div>
</div>
{% endblock %}

ecommerce_site/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        We have plenty variety of products
{% endblock %}


{% block title %}
   search
{% endblock %}

{% block body %}
<div>
        <p class="text-center my_search">You are searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">

        {% for product in products  %}

        <div class="my_bottom_margin col-sm-4 ">
            <div class="card text-center" style="min-width:14rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url }}" alt="{{product.name}}"></a>

             <div class="card-body">

                <h3>{{product.name}}</h3>
                <p>${{product.price}}</p>
            <br><br>
            </div>

             </div>

        </div>

                {% empty %}
            <div>
                <p class="text-center my_search"> 0 results found</p>
            </div>
            {% endfor %}
    </div>
</div>

{% endblock %}